# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NormalizationCPP_config = debug

else ifeq ($(config),release)
  NormalizationCPP_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := NormalizationCPP

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

NormalizationCPP:
ifneq (,$(NormalizationCPP_config))
	@echo "==== Building NormalizationCPP ($(NormalizationCPP_config)) ===="
	@${MAKE} --no-print-directory -C NormalizationCPP -f Makefile config=$(NormalizationCPP_config)
endif

clean:
	@${MAKE} --no-print-directory -C NormalizationCPP -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NormalizationCPP"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"